Fix warning using ERR_FAIL_INDEX on unsigned int
This method starting being used in 9fb6054f8747f6773acab35d2ff17e1d3330317e,
which now triggers this warning from GCC 10:
```
./core/error_macros.h:151:25: error: comparison of unsigned expression in '< 0' is always false [-Werror=type-limits]
```