Fix warning using ERR_FAIL_INDEX on unsigned int
This method starting being used in a813968e0abb5cc1c7fc9faa84085f549903fbe3,
which now triggers this warning from GCC 10:
```
./core/error_macros.h:151:25: error: comparison of unsigned expression in '< 0' is always false [-Werror=type-limits]
```